[tool.poetry]
version = "1.0.0"
name = "src"
description = "orca backend serves as nms"
authors = ["Kamal Krishna Bhatt <kamal.bhatt@stordis.com>"]

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0"
neo4j = "^5.4.0"
grpcio-tools = "^1.51.1"
requests = "^2.28.2"
Django = "^4.1.5"
django-rest-framework = "^0.1.0"
nornir = "^3.3.0"
napalm = "^4.0.0"




